"""empty message

Revision ID: 79680e571b5a
Revises: b7ad45db57fd
Create Date: 2022-03-05 22:32:56.305701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79680e571b5a'
down_revision = 'b7ad45db57fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
